framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
<<<<<<< HEAD
<<<<<<< HEAD
        message_bus: false  
=======
>>>>>>> chiheb+walaa/syrinecopie_branch
=======
        message_bus: false  
>>>>>>> 6f2e479 (walaa+bundles)
