vich_uploader:
    db_driver: orm
    mappings:
        event_image:
            uri_prefix: /images/events
            upload_destination: '%kernel.project_dir%/public/images/events'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true