#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_home:
    path: /
    controller: App\Controller\HomeController::index
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
send_email:
    path: /send-email
    controller: App\Controller\EmailController::sendEmail
=======

event_participate:
    path: /event/{id}/participate
    controller: 'App\Controller\EventController::participate'     
>>>>>>> chiheb+walaa/syrinecopie_branch
=======
send_email:
    path: /send-email
    controller: App\Controller\EmailController::sendEmail
>>>>>>> 6f2e479 (walaa+bundles)
=======
send_email:
    path: /send-email
    controller: App\Controller\EmailController::sendEmail
>>>>>>> c98b2fa (walaa+chiheb integration)
=======
send_email:
    path: /send-email
    controller: App\Controller\EmailController::sendEmail
>>>>>>> 8b6d46d (Rayen)
